-- AlterTable
ALTER TABLE "users" ADD COLUMN     "address" TEXT,
ADD COLUMN     "companyDescription" TEXT,
ADD COLUMN     "companyName" TEXT,
ADD COLUMN     "companySize" TEXT,
ADD COLUMN     "currency" TEXT DEFAULT 'USD',
ADD COLUMN     "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "industry" TEXT,
ADD COLUMN     "language" TEXT DEFAULT 'en',
ADD COLUMN     "loginNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "newMessages" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "paymentUpdates" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "placeId" TEXT,
ADD COLUMN     "projectUpdates" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "theme" TEXT DEFAULT 'light',
ADD COLUMN     "timezone" TEXT,
ADD COLUMN     "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "website" TEXT;
